server:
  port: 7777

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
            - Path=/cloud/user/**
          filters:
            - RewritePath=/cloud/user/(?<s>.*), /${s}
          uri: lb://ms-datacenter
        - id: route2
          predicates:
            - Path=/cloud/datacenter/**
          filters:
            - RewritePath=/cloud/datacenter/(?<s>.*), /${s}
          uri: lb://ms-datacenter
